### ISSUE TITLE
Calculating MZDeviation values

### ISSUE THREAD

**Issue by laurenmm** [christophuv/PeakBot_Example#1]
Hi! I'm wondering how you calculated the MZDeviation values for the wall and peaks input files.

**Comment by chrboku** [comment]
Hello

If you refer to for example this example file
https://github.com/christophuv/PeakBot_Example/blob/main/Reference/MTBLS797_Walls.tsv

The MZDeviation is derived from manual inspection of such walls (for the examples). I looked at the raw data with TOPPView and then took approximately the area where no longer MZ Peaks of the particular wall are present (see image), multiplied that by 2 and rounded.
So it is a manually derived and estimated value rather than a calculation derived one. However, I saw little difference between smaller and larger windows. 

Hope this helps, best regards, christoph

![image](https://github.com/christophuv/PeakBot_Example/assets/18591761/b240338b-13cc-420f-9107-091f0c24c5b1)
